#define VODKA 1
#define RHUM 2
#define GIN 3
#define COINTREAU 4
#define MOJITO 5
#define PUNCH 6
#define LAGOON 7
#define LONG 8
#define DAIKIRI 9
#define CUBA 10
#define GIN 11
#define ZIZI 12
#define SCREW 13
#define TOM 14
#define COSMO 15
#define GOD 16
#define HAWAIIAN 17
#define LION 18
#define CLOVER 19
#define SILVER 20
#define BLOSSOM 21
#define BALALAIKA 22
#define SCOUR 23
